version: '2'

services:
  config-server:
    image: petclinic-config-server:DEV
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888

  discovery-server:
    image: petclinic-discovery-server:DEV
    container_name: discovery-server
    mem_limit: 512M
    ports:
      - 8761:8761
    depends_on:
      - config-server
    entrypoint: ["./dockerize", "-wait=tcp://config-server:8888", "-timeout=160s", "--", "java", "-Djava.security"]

  customers-service:
    image: petclinic-customers-service:DEV
    container_name: customers-service
    mem_limit: 512M
    ports:
     - 8081:8081
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security"]

  visits-service:
    image: petclinic-visits-service:DEV
    container_name: visits-service
    mem_limit: 512M
    ports:
     - 8082:8082
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security"]

  vets-service:
    image: petclinic-vets-service:DEV
    container_name: vets-service
    mem_limit: 512M
    ports:
     - 8083:8083
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security"]

  api-gateway:
    image: petclinic-api-gateway:DEV
    container_name: api-gateway
    mem_limit: 512M
    ports:
     - 8080:8080
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security"]

  admin-server:
    image: petclinic-admin-server:DEV
    container_name: admin-server
    mem_limit: 512M
    ports:
     - 9090:9090
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security"]

  hystrix-dashboard:
    image: petclinic-hystrix-dashboard:DEV
    container_name: hystrix-dashboard
    mem_limit: 512M
    ports:
     - 7979:7979
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security"]

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - 9411:9411

  grafana-server:
    image: petclinic-grafana-server:DEV
    container_name: grafana-server
    mem_limit: 256M
    ports:
    - 3000:3000

  prometheus-server:
    image: petclinic-prometheus-server:DEV
    container_name: prometheus-server
    mem_limit: 256M
    ports:
    - 9091:9090

  mysql-server:
    image: mysql:5.7.8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    mem_limit: 256M
    ports:
    - 3306:3306
